export const API_ROUTES = {
    LOGIN: '/api/auth/login',
    REGISTER: '/api/auth/register',
    REFRESH: '/api/auth/refresh',
    RESET_PASSWORD: '/api/auth/resetPassword',
    RESET_PASSWORD_REQUEST: '/api/auth/resetPasswordRequest',
    USER_BY_ID: '/api/user',
    USER_PROFILE: '/api/user/profile',
    VERIFY_2FA: '/api/auth/2FA',
    RESEND_2FA: '/api/auth/2FA/resend',
    STATUS_2FA: '/api/auth/2FA/status',
    USER_GROUPS: '/api/user/groups',
    GROUP_BY_ID: '/api/group',
    ADD_GROUP: '/api/group',
    LOGOUT: '/api/auth/logout',
    JOIN_GROUP: '/api/group/join',
    IS_ADMIN: '/api/group/isAdmin',
    GET_GROUP_MEMBERS: '/api/group/members',
    GET_JOIN_REQUESTS: '/api/user/joinRequest',
    GENERATE_JOIN_GROUP_CODE: '/api/group/generateJoinCode',
} as const; 