import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import { AuthProvider } from '@/contexts/AuthContext';
import { ThemeProvider, GroupThemeUpdater } from '@/styles/theme';
import '@/styles/globals.css';

const nunito = Nunito({
  variable: "--font-nunito",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
});


export const metadata: Metadata = {
  title: "Mates",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta name="theme-color" content="#9042fb" />
      </head>
      <body
        className={`${nunito.variable} antialiased`}
      >
        <ThemeProvider>
          <AuthProvider>
            <GroupThemeUpdater />
            {children}
          </AuthProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
